[project]
name = "keyword-generator-main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hemanth-33", email = "hemanthreddy5360@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.142.2",
    "uvicorn>=0.54.0",
]

[project.scripts]
keyword-generator-main = "keyword_generator_main:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
